config/routes.rb
Rails.application.routes.draw do

  resources :reservations
  resources :vols

  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

  get "vol/vol"
  get 'home/private'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :vol
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reservations
end

app/models/vol.rb
class Vol < ApplicationRecord
  has_many :reservations


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def private
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @vol = Vol.find(params[:vol_id])
    @reservation = Reservation.new
    @reservation.vol_id = @vol.id
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    respond_to do |format|
      if @reservation.save
        # Tell the UserMailer to send a welcome email after save
        ReservationMailer.send_reservation_mail(@reservation.user, @reservation).deliver_now

        format.html { redirect_to @reservation, notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:classe, :code, :nb_passager, :vol_id)
    end
end

app/controllers/vols_controller.rb
class VolsController < ApplicationController
  require 'pagy/extras/array'

  before_action :set_vol, only: %i[ show edit update destroy ]

  # GET /vols or /vols.json
  def index
    @pagy, @vols = pagy_array(Vol.all.select{ |v| v.date_heure_dep.future? }.to_ary, item: 5)
  end

  # GET /vols/1 or /vols/1.json
  def show
  end

  # GET /vols/new
  def new
    @vol = Vol.new
  end

  # GET /vols/1/edit
  def edit
  end

  # POST /vols or /vols.json
  def create
    @vol = Vol.new(vol_params)

    respond_to do |format|
      if @vol.save
        format.html { redirect_to @vol, notice: "Vol was successfully created." }
        format.json { render :show, status: :created, location: @vol }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vols/1 or /vols/1.json
  def update
    respond_to do |format|
      if @vol.update(vol_params)
        format.html { redirect_to @vol, notice: "Vol was successfully updated." }
        format.json { render :show, status: :ok, location: @vol }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vols/1 or /vols/1.json
  def destroy
    @vol.destroy
    respond_to do |format|
      format.html { redirect_to vols_url, notice: "Vol was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vol
      @vol = Vol.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vol_params
      params.require(:vol).permit(:numero, :aeroport_dep, :aeroport_arr, :date_heure_dep, :date_heure_arr)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/vols_helper.rb
module VolsHelper
end

app/views/home/_header.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #080336;">
  <span class="navbar-text">
    <% if !user_signed_in? %>

      <%= link_to "Accueil", vols_path, class: 'link-light nav-link', style: 'font-weight: bold;' %>
    <% else %>
      <%= link_to "Accueil", "/" , class: 'link-secondary nav-link', style: 'font-weight: bold;' %>
    <% end %>


  </span>
  <% if user_signed_in? %>
  <span class="navbar-text">
    <%= link_to "Liste vol", vols_path, class: 'link-light nav-link', style: 'font-weight: bold;' %>
  </span>
  <% end %>
  <% if user_signed_in? %>
    <span class="navbar-text">
      <%= link_to "Mes vols", reservations_path, class: 'link-light nav-link', style: 'font-weight: bold;' %>
    </span>
  <% end %>
  <% if user_signed_in? %>
    <span class="navbar-text">
      <%= link_to "Mon compte", edit_user_registration_path, class: 'link-light nav-link', style: 'font-weight: bold;' %>
    </span>
  <% end %>
  <% if !user_signed_in? %>
    <span class="navbar-text">
      <%= link_to "Login", new_user_session_path, class: 'link-light nav-link', style: 'font-weight: bold;' %>
    </span>
  <% end %>

    <% if user_signed_in? %>
      <span class="navbar-text">
        Vous etes connecté avec : <strong><%= current_user.email %></strong>.
      </span>
      <span class="navbar-text">
        <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: 'link-light nav-link', style: 'font-weight: bold;'  %>
      </span>
    <% else %>
      <span class="navbar-text">
        <%= link_to "Inscription", new_user_registration_path, class: 'link-light nav-link', style: 'font-weight: bold;'  %>
      </span>
    <% end %>

  <span class="navbar-text">
      <%= link_to "paths", "/userjse", class: 'link-light nav-link', style: 'font-weight: bold;' %>
    </span>

</nav>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjetRuby</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= render "header" %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>


<h1 style="text-align: center">Acceuil</h1>

<div class="container">
<!--  <img src="https://ibp.info6tm.fr/api/v1/images/view/5c505b5e8fe56f45823a2e98/article/image.jpg" alt="Aeroport" />-->

</div>


</body>
</html>

app/views/home/private.html.erb
<h1>Home#private</h1>
<p>Find me in app/views/home/private.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render "home/header" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "home/navbar" %>
    <%= yield %>


  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<!--  <div class="field">-->
    <%#= form.label :classe, value:"Classe affaire ?" %>
<!--    <br><%#= radio_button_tag :classe, "economique", true %> economique-->
<!--    <br><%#= radio_button_tag :classe, "affaire" %> affaire-->
<!--    <br><%#= radio_button_tag :classe, "premiere" %> Première-->
<!--  </div>-->


  <div class="field">
    <%= form.label :classe %>
    <%= form.text_field :classe %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, value: + 1 + rand(1000...9998), :readonly => "true"%>
  </div>

  <div class="field">
    <%= form.label :nb_passager %>
    <%= form.number_field :nb_passager %>
  </div>

  <%= form.hidden_field(:vol_id) %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>
<div class="container">
<table class="table">
  <thead>
  <tr>
    <th>Classe</th>
    <th>Code</th>
    <th>Nb passager</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% current_user.reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.classe %></td>
        <td><%= reservation.code %></td>
        <td><%= reservation.nb_passager %></td>
        <!--        <td><%#= link_to 'Show', reservation %></td>-->
<!--        <td><%#= link_to 'Edit', edit_reservation_path(reservation) %></td>-->
        <td><%= link_to 'Supprimer', reservation, method: :delete, data: { confirm: 'Cette suppression est irréversible. Voulez vous continuer ? ' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
</div>

<br>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Classe:</strong>
  <%= @reservation.classe %>
</p>

<p>
  <strong>Code:</strong>
  <%= @reservation.code %>
</p>

<p>
  <strong>Nb passager:</strong>
  <%= @reservation.nb_passager %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/vols/_form.html.erb
<%= form_with(model: vol) do |form| %>
  <% if vol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vol.errors.count, "error") %> prohibited this vol from being saved:</h2>

      <ul>
        <% vol.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero %>
  </div>

  <div class="field">
    <%= form.label :aeroport_dep %>
    <%= form.text_field :aeroport_dep %>
  </div>

  <div class="field">
    <%= form.label :aeroport_arr %>
    <%= form.text_field :aeroport_arr %>
  </div>

  <div class="field">
    <%= form.label :date_heure_dep %>
    <%= form.datetime_select :date_heure_dep %>
  </div>

  <div class="field">
    <%= form.label :date_heure_arr %>
    <%= form.datetime_select :date_heure_arr %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vols/_reservation.html.erb
<%= form_with(model: vol) do |form| %>
  <% if vol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vol.errors.count, "error") %> prohibited this vol from being saved:</h2>

      <ul>
        <% vol.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :"nombre passager" %>
    <%= form.number_field :nb, in: 1..99, step: 1 %>
  </div>

  <div class="field">
    <%= form.label :"Classe affaire ?" %>
    <br><%= radio_button_tag "classe", "economique", true %> economique
    <br><%= radio_button_tag "classe", "affaire" %> affaire
    <br><%= radio_button_tag "classe", "premiere" %> Première
  </div>




  <div class="actions">
    <%= form.submit %>
  </div>



  <%= link_to 'New Reservation', new_reservation_path(vol_id: @vol.id) %>
<% end %>

app/views/vols/edit.html.erb
<h1>Editing Vol</h1>

<%= render 'form', vol: @vol %>

<%= link_to 'Show', @vol %> |
<%= link_to 'Back', vols_path %>

app/views/vols/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

<h1>Vols</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Numero</th>
        <th>Aeroport départ</th>
        <th>Aeroport arrivé</th>
        <th>Date heure départ</th>
        <th>Date heure arrivé</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @vols.each do |vol| %>
        <tr>
          <td><%= vol.numero %></td>
          <td><%= vol.aeroport_dep %></td>
          <td><%= vol.aeroport_arr %></td>
          <td><%= vol.date_heure_dep %></td>
          <td><%= vol.date_heure_arr %></td>

          <td><%= link_to 'Afficher', vol %></td>
         <!-- <td><%#= link_to 'Show', vol %></td>
          <td><%#= link_to 'Edit', edit_vol_path(vol) %></td>
          <td><%#= link_to 'Destroy', vol, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        </tr>
      <% end %>
    </tbody>
  </table>

  <%== @vols.count %> / <%== Vol.count %>

  <%== pagy_nav(@pagy) %>

</div>

<br>

<%= link_to 'New Vol', new_vol_path %>

app/views/vols/new.html.erb
<h1>New Vol</h1>

<%= render 'form', vol: @vol %>

<%= link_to 'Back', vols_path %>

app/views/vols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @vol.numero %>
</p>

<p>
  <strong>Aeroport dep:</strong>
  <%= @vol.aeroport_dep %>
</p>

<p>
  <strong>Aeroport arr:</strong>
  <%= @vol.aeroport_arr %>
</p>

<p>
  <strong>Date heure dep:</strong>
  <%= @vol.date_heure_dep %>
</p>

<p>
  <strong>Date heure arr:</strong>
  <%= @vol.date_heure_arr %>
</p>

<% if user_signed_in? %>
  <%= link_to 'Réserver ce vol', new_reservation_path(vol_id: @vol.id) %>
<% else %>
  <td> <%= link_to "Réserver ce vol", new_user_session_path, method: :new_user_session_path, data: { confirm: 'Vous devez vous identifier pour réserver un vol. Voulez vous continuer ?' }%> </td>
<% end %>